### ISSUE TITLE
language with reverse geocode

### ISSUE THREAD

**Issue by rami1973** [lase-peco/geocoder#2]
$g=Geocoder::reverse($lat,$lng)->language($lang) ;

    print_r($g);
give me:
Call to undefined method Geocoder\Laravel\ProviderAndDumperAggregator::language()

**Comment by ahmeddabak** [comment]
The `reverse`method returns a collection that you can iterate though, it does not have a `language`method.

What you need to call is `$g = Geocoder::language( $lang )->reverse( $lat , $lng );`

Furthermore, please ensure that the package is not conflicting with other Geocoding packages like this one `https://github.com/geocoder-php/GeocoderLaravel`
